//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int id_Product { get; set; }
        public Nullable<int> id_Supply { get; set; }
        public Nullable<int> id_Kind { get; set; }
        public string Name_Product { get; set; }
        public int PurchaseCost { get; set; }
        public int SellingPrice { get; set; }
        public int Amount_Product { get; set; }
        public string Photo { get; set; }
    
        public virtual Kind Kind { get; set; }
        public virtual Supply Supply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
