//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id_User { get; set; }
        public string Surname_User { get; set; }
        public string Name_User { get; set; }
        public string Patronymic_User { get; set; }
        public int id_Gender { get; set; }
        public string Login { get; set; }
        public int Password { get; set; }
        public System.DateTime Birthday_User { get; set; }
        public int id_Role { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
    }
}
