//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPhoto
    {
        public int id_Photo { get; set; }
        public int id_User { get; set; }
        public byte[] Photo_Binary { get; set; }
        public string Photo_Path { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
